### ISSUE TITLE
error has the wrong upper bound

### ISSUE THREAD

**Issue by cx19981114** [ingonyama-zk/modular_multiplication#1]
Hi!
I have noticed that in the calculation of `LS`, there is a judgment on whether z meets the extra output bit of LSB

https://github.com/ingonyama-zk/modular_multiplication/blob/59c19ec2c824025cf6c9ccad0a91f82ccacd5814/domb_barrett_mp.py#L37-L48

but this judgment is not consistent with the paper

<img width="909" alt="image" src="https://user-images.githubusercontent.com/37799218/217453578-e52c8430-9b8c-49dd-9697-ae4f6f092e47.png">

and this judgment is not consistent with the following error upper bound judgment

https://github.com/ingonyama-zk/modular_multiplication/blob/59c19ec2c824025cf6c9ccad0a91f82ccacd5814/domb_barrett_mp.py#L53

Is there something wrong with this judgment？

**Comment by omershlo** [comment]
Thank you @cx19981114 ! 
@IdoAtlas @Tomer-Solberg @yuvalingo

**Comment by IdoAtlas** [comment]
Hey, you are right! the formula in the paper is the correct one. changed it accordingly in the code. Thanks for the feedback!
